### ISSUE TITLE
RequestNpcPacket needs to be more flexible

### ISSUE THREAD

**Issue by Adanlink** [ChickenAPI/ChickenAPI.Packets#53]
The PacketIndex(2) more known as Data is nullable because it's optional. Adding IsOptional = True is required to fix this decoding error when trying to interact with an NPC
(Tried on NosCore)
![img](https://gyazo.com/1f7bba54e9dc344ffd5c1abb28180ff9.png)

**Comment by Adanlink** [comment]
Idk, why but the error still persists on NosCore...
![img](https://gyazo.com/8d1fb42e470ef2bd09cd2b45ba9aebf5.png)
Even when the optionality is triggered, maybe this has something to do with something I don't understand.
(Btw, I'm using the 0.4.10)

**Comment by 0Lucifer0** [comment]
Yes noscore need to update the package
