### ISSUE TITLE
In packet is invalid

### ISSUE THREAD

**Issue by 0Lucifer0** [ChickenAPI/ChickenAPI.Packets#58]
https://github.com/NosCoreIO/NosCore/issues/539

**Comment by 0Lucifer0** [comment]
I think there is just a space between upgrade and rarity like it should have always been.

**Comment by BlowaXD** [comment]
Can someone with latest client send some details about the new packet's template ?
I'd like to fix it.

**Comment by 0Lucifer0** [comment]
“Thx for reporting it, actually this bug is from the InPacket.cs and InCharacterSubPacket.cs from ChickenAPI that needs an update/fix.

"in 1 [Support]test2 2 21 3 2 1 1 0 9 0 -1.-1.-1.-1.-1.-1.-1.-1.-1 100 100 0 -1 0 0 0 0 0 0 00 00 -1 1 0 0 0 0 1 0 0 500 10 0" - Actual NosCore (In packet from a character without familiy)

"in 1 Someone - 12345 66 106 2 0 1 1 9 3 -1.120.149.86.-1.802.-1.8082.-1.-1 100 100 0 20 4 3 0 0 0 2518 1 0 -1 - 9 0 0 0 0 29 0 0|0|0 0 0 10 0" - Actual Nostale-US-Cylloan

InPacket.cs - Vnum should be optional.

InCharacterSubPacket.cs - Jesus, a lot of things to change, or maybe fix.”
