### ISSUE TITLE
Strange decoding error

### ISSUE THREAD

**Issue by Adanlink** [ChickenAPI/ChickenAPI.Packets#60]
Sended this "npc_req 2 2075"

And got this from NosCore GameServer's Console![img](https://gyazo.com/00270a52e60c435a53512ac9126a002e.png)

Actual Packet.cs -> ![img](https://gyazo.com/d24eceadca60f9868bd408bfef774dcd.png)

**Comment by 0Lucifer0** [comment]
doesn't seems to be linked to chickenapi will see in noscore.
