### ISSUE TITLE
PacketIndex with nullable enum fails to be parsed

### ISSUE THREAD

**Issue by Adanlink** [ChickenAPI/ChickenAPI.Packets#70]
![img](https://gyazo.com/b4aa58e99a26c3c3a6cc53a362ce8ec2.png)
![img](https://gyazo.com/a3edb0ef03481987b7469f0d3cad39c1.png)

**Comment by 0Lucifer0** [comment]
We need to replace type by Nullable.GetUnderlyingType(type) ?? type
